# -*- coding: utf-8 -*-
"""Predictive Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJ_3NTGpkGqoZq3wHH_sp825eiz2xfVX

# **Predictive Analytics: Harga Beras Medium**


---

## **Deskripsi Proyek**

### **Latar Belakang**

Harga rumah merupakan salah satu aspek krusial dalam industri properti. Calon pembeli, investor, maupun developer membutuhkan informasi estimasi harga rumah berdasarkan karakteristik tertentu seperti luas bangunan, jumlah kamar, hingga kapasitas garasi. Prediksi harga rumah yang akurat dapat membantu pengambilan keputusan investasi serta menentukan strategi pemasaran properti.

## **1. Import Library yang Dibutuhkan**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""## **2. Data Understanding**

Bagian ini merupakan proses mulai dari memuat sampai dengan meninjau dataset yang akan dianalisis dalam proyek prediksi harga rumah. Tujuannya dari proses ini memahami dan mendapatkan gambaran secara umum mengenai struktur data, isi data, dan kualitas data, sehingga dapat membantu proses persiapan data dan pembangunan model

### **Data Loading**
"""

url = "https://raw.githubusercontent.com/Meio047/Predictive-Analytics/refs/heads/main/data_rumah.csv"
df = pd.read_csv(url)

df

"""### **Exploratory Data Analysis (EDA)**

Exploratory Data Analysis (EDA) merupakan proses eksplorasi untuk mengamati dan menganilis data untuk melihat pola, tren dan karakteristik data dalam dataset. Tujuannya untuk menemukan insight awal yang dapat membantu menentukan metode dan model yang dapat digunakan untuk analisis selanjutnya

### **EDA - Deskripsi Variabel**
"""

df = df.rename(columns={
    'NO': 'nomor',
    'NAMA RUMAH': 'nama_rumah',
    'HARGA': 'harga',
    'LB': 'lb',
    'LT': 'lt',
    'KT': 'kt',
    'KM': 'km',
    'GRS': 'grs'
})
df.head()

df.info()

df.describe()

df.shape

"""Insight:

- Dataset terdiri dari 1010 baris data dengan 8 kolom yang merepresentasikan detail rumah yang akan dijual.

- Variabel yang ada meliputi:
    1. nomor : no
    2. nama_rumah : nama detail rumah
    3. harga : harga rumah
    4. lb : luas bangunan
    5. lt : luas tanah
    6. kt : jumlah kamar tidur
    7. km : jumlah kamar mandi
    8. grs : jumlah mobil yang dapat ditampung oleh garasi
    
- Dataset terdiri dari 1.010 data rumah yang dijual dengan 8 variabel. Tipe data yang terdapat adalah: satu variabel bertipe objek (string), tujuh variable bertipe integer(int64)

### **EDA - Menangani Missing Value dan Outliers**
"""

df.duplicated().sum()

df.isnull().sum()

plt.figure()
sns.boxplot(df, x='harga')
plt.show()

Q1 = df['harga'].quantile(0.25)
Q3 = df['harga'].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df['harga'] < (Q1 - 1.5 * IQR)) | (df['harga'] > (Q3 + 1.5 * IQR)))]

plt.figure(figsize=(6, 5))
sns.boxplot(data=df, x='harga', whis=[0, 100])
plt.title("Boxplot Harga")
plt.show()

df.shape

"""Insight :
- Dataset tidak memiliki nilai duplikat dan tidak memiliki nilai yang hilang(missiing balue)
- Dengan visualisasi boxplot diatas `harga` memiliki outlier dan sudah ditangani menggunakan Inter Quartile Range (IQR)
`IQR = Q3 - Q1`

### **Univariate Analysis**

Tahapan ini bertujuan untuk melihat distribusi data masing masing fitur
"""

# Drop data yang tidak digunakan
df.drop(columns=['nomor', 'nama_rumah'], inplace=True, errors='ignore')

#Mengganti satuan harga agar lebih readable
df['harga'] = (df['harga']/1000000).astype(int)

df.head()

q1 = df['harga'].quantile(0.25)
median = df['harga'].median()
q3 = df['harga'].quantile(0.75)

def classification_harga(harga):
    if harga <= q1:
        return 'Murah'
    elif harga <= median:
        return 'Menengah'
    else:
        return 'Mahal'

# Menambahkan kolom baru
df['tingkat_harga'] = df['harga'].apply(classification_harga)

df.head()

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='tingkat_harga', order=['Murah', 'Menengah', 'Mahal'], palette='rocket')
plt.title('Jumlah rumah dalam Setiap Kategori Harga')
plt.xlabel('Kategori Harga')
plt.ylabel('Jumlah Rumah')
plt.show()

df['tingkat_harga'].value_counts()

plt.figure(figsize=(10, 8))
sns.histplot(df['harga'], kde=True)
plt.title('Distribusi Harga')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(df['lb'], kde=True)
plt.title('Distribusi Luas Bangunan')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(df['lt'], kde=True)
plt.title('Distribusi Luas Tanah')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(df['kt'], kde=True)
plt.title('Distribusi Jumlah Kamar Tidur')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(df['km'], kde=True)
plt.title('Distribusi Jumlah Kamar Mandi')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(df['grs'], kde=True)
plt.title('Distribusi Jumlah Garasi')
plt.show()

numeric = ['harga', 'lb', 'lt', 'kt', 'km', 'grs']

plt.figure(figsize=(8,6))
sns.heatmap(df[numeric].corr(), annot=True, cmap='coolwarm')
plt.title('Korelasi antar fitur numerik')
plt.show()

"""### **Multivariate Analysis**

Menjelaskan hubungan antar variable
"""

# Scatterplot untuk fitur kontinu
for kolom in ['lb', 'lt']:
    plt.figure(figsize=(6,4))
    sns.scatterplot(x=df[kolom], y=df['harga'])
    plt.title(f'Harga vs {kolom}')
    plt.show()

# Boxplot untuk fitur kategori (jumlah kamar, garasi)
for kolom in ['kt', 'km', 'grs']:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[kolom], y=df['harga'], whis=[0, 100])
    plt.title(f'Harga vs {kolom}')
    plt.show()

"""## **3. Data Preparation**

### **Pemilihan Fitur**
"""

# Pisahkan fitur (X) dan target (y)
X = df[['lb', 'lt', 'kt', 'km', 'grs']]
y = df['harga']

"""### **Split Data**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Total datasets: {len(X)}')
print(f'Total data Latih: {len(X_train)}')
print(f'Total data Uji: {len(X_test)}')

"""### **Normalisasi**"""

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## **4. Pembuatan Model**

- **Linear Regression**
"""

# Linear Regression
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)

"""- **Decision Tree**"""

# Decision Tree
dt = DecisionTreeRegressor(max_depth=5)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

"""- **Random Forest**"""

# Random Forest
rf = RandomForestRegressor(n_estimators=100, max_depth=7)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

"""- **Gradient Boosting**"""

# Gradient Boosting
gbr = GradientBoostingRegressor()
gbr.fit(X_train, y_train)
y_pred_gbr = gbr.predict(X_test)

"""## **5. Evaluasi Model**

Evaluasi model menggunakan MAE, MSE, RMSE, R² Score untuk mengukur error atau kesalahan prediksi sebagai acuan kualitas model secara keseluruhan
"""

# Evaluasi dan simpan dalam DataFrame
results = []
models = [("Linear Regression", lr, y_pred_lr),
          ("Decision Tree", dt, y_pred_dt),
          ("Random Forest", rf, y_pred_rf),
          ("Gradient Boosting", gbr, y_pred_gbr)]

for name, model, y_pred in models:
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)  # Calculate RMSE
    r2 = r2_score(y_test, y_pred)
    results.append([name, mae, mse, rmse, r2])

eval_df = pd.DataFrame(results, columns=["Model", "MAE", "MSE", "RMSE", "R2"])

# Tampilkan tabel evaluasi
eval_df

"""### **Plot Model Hasil Evaluasi**"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Perbandingan Performa Antar Model', fontsize=16)

metrics = ["MAE", "MSE", "RMSE", "R2"]
positions = [(0, 0), (0, 1), (1, 0), (1, 1)]

for metric, pos in zip(metrics, positions):
    ax = axes[pos]
    sns.barplot(x='Model', y=metric, data=eval_df, ax=ax)
    ax.set_title(f'{metric}')
    ax.set_xlabel('')
    ax.set_ylabel(metric)

plt.tight_layout(rect=[0, 0, 1, 0.95])  # Supaya tidak bertabrakan dengan suptitle
plt.show()

"""**Insight dari Evaluasi Model Prediksi Harga rumah**

- Berdasarkan metrik evaluasi, model Random Forest menunjukkan performa terbaik dibandingkan model lainnya.
- Hal ini terlihat dari nilai R² tertinggi, yang mendekati 1, menandakan bahwa model mampu menjelaskan proporsi variasi terbesar dari harga beras.
- MAE (Mean Absolute Error) dan RMSE (Root Mean Squared Error) untuk Random Forest juga yang paling kecil di antara ketiga model.

Berdasarkan evaluasi maka Random Forest adalah model yang paling handal



"""